AWSTemplateFormatVersion: '2010-09-09'
Description: 'Global API Gateway Account Configuration for CloudWatch Logging'

Resources:
  ApiGatewayCloudWatchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'

  ApiGatewayAccount:
    Type: 'AWS::ApiGateway::Account'
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn

Outputs:
  ApiGatewayCloudWatchRoleArn:
    Description: ARN of the IAM role used for CloudWatch logging
    Value: !GetAtt ApiGatewayCloudWatchRole.Arn