FROM python:3.9-slim
RUN apt-get update && \
    apt-get install -y \
    curl \
    unzip \
    groff \
    less \
    && apt-get clean
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip
RUN pip install --no-cache-dir aws-sam-cli
ENV SAM_CLI_TELEMETRY=0
WORKDIR /sam
ENTRYPOINT ["sam"]