FROM python:3.9-slim
RUN apt-get update && \
    apt-get install -y \
    curl \
    unzip \
    groff \
    less \
    && apt-get clean
RUN pip install --no-cache-dir aws-sam-cli
ENV SAM_CLI_TELEMETRY=0
WORKDIR /sam
ENTRYPOINT ["sam"]