services:
  sam:
    build:
      context: .
      dockerfile: Dockerfile.sam
    volumes:
      - .:/sam
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    environment:
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - SAM_CLI_CONTAINER_CONNECTION_TIMEOUT=60
    networks:
      - dog-walking

  bootstrap:
    build:
      context: .
      dockerfile: Dockerfile.bootstrap
    container_name: bootstrap
    volumes:
      - .:/app

  acceptance-test:
    build:
      context: .
      dockerfile: Dockerfile.acceptance
    container_name: acceptance-test
    environment:
      - API_HOST=api.uat.dog-walking.roberthargreaves.com
    networks:
      - dog-walking

networks:
  dog-walking:
    name: dog-walking
