services:
  sam:
    depends_on:
      localstack:
        condition: service_healthy
    image: ghcr.io/rhargreaves/aws-sam-cli:1.135.0
    volumes:
      - .:/sam
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /sam
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 5s
      timeout: 2s
      retries: 10
    environment:
      - SAM_CLI_CONTAINER_CONNECTION_TIMEOUT=10
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    command: >
      local start-api
      --host 0.0.0.0
      --container-host-interface 0.0.0.0
      --container-host ${CONTAINER_HOST}
      --docker-volume-basedir ${PROJECT_ROOT}
      --docker-network dog-walking_default
      --skip-pull-image
      --warm-containers EAGER

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - GATEWAY_LISTEN=0.0.0.0:4566
    volumes:
      - ./infra/localstack:/etc/localstack/init/ready.d
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 2s
      retries: 3
    networks:
      default:
        aliases:
          - local-dog-images.s3.localhost.localstack.cloud

  e2e-test:
    build:
      context: test/e2e
      dockerfile: Dockerfile
    container_name: e2e-test
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - API_BASE_URL
      - AWS_REGION
      - USE_LOCALSTACK=false
      - DOG_IMAGES_BUCKET
      - COGNITO_USER_POOL_NAME
      - COGNITO_CLIENT_NAME
      - COGNITO_USERNAME
      - COGNITO_PASSWORD

  e2e-test-local:
    depends_on:
      sam:
        condition: service_healthy
    build:
      context: test/e2e
      dockerfile: Dockerfile
    container_name: e2e-test-local
    environment:
      - API_BASE_URL=http://sam:3000
      - LOCAL_JWT_SECRET
      - AWS_REGION
      - USE_LOCALSTACK=true
      - AWS_S3_ENDPOINT_URL=http://s3.localhost.localstack.cloud:4566
      - DOG_IMAGES_BUCKET=local-dog-images
