services:
  sam:
    depends_on:
      localstack:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.sam
    volumes:
      - .:/sam
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 5s
      timeout: 2s
      retries: 10
    environment:
      - SAM_CLI_CONTAINER_CONNECTION_TIMEOUT=10
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    command: >
      local start-api
      --host 0.0.0.0
      --container-host-interface 0.0.0.0
      --container-host ${CONTAINER_HOST}
      --docker-volume-basedir ${WORKDIR}
      --docker-network dog-walking_default

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - LS_LOG=trace
      - GATEWAY_LISTEN=0.0.0.0:4566
    volumes:
      - ./infra/localstack:/etc/localstack/init/ready.d
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 2s
      retries: 3

  acceptance-test:
    build:
      context: test/acceptance
      dockerfile: Dockerfile
    container_name: acceptance-test
    environment:
      - API_BASE_URL

  acceptance-test-local:
    depends_on:
      sam:
        condition: service_healthy
    build:
      context: test/acceptance
      dockerfile: Dockerfile
    container_name: acceptance-test-local
    environment:
      - API_BASE_URL=http://sam:3000