AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      BinaryMediaTypes:
        - image/jpeg

  HttpApiNoAuth:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "http://localhost:3001"
        AllowHeaders:
          - "content-type"
          - "authorization"
        AllowMethods:
          - "*"
        MaxAge: 600
        AllowCredentials: true

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "http://localhost:3001"
        AllowHeaders:
          - "content-type"
          - "authorization"
        AllowMethods:
          - "*"
        MaxAge: 600
        AllowCredentials: true
      Auth:
        DefaultAuthorizer: LocalAuth
        Authorizers:
          LocalAuth:
            AuthorizerPayloadFormatVersion: '1.0'
            FunctionArn: !GetAtt LocalAuthFunction.Arn
            Identity:
              Headers:
                - Authorization


  LocalAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: local-auth/build/
      Handler: bootstrap
      Runtime: provided.al2023
      Environment:
        Variables:
          LOCAL_JWT_SECRET: "1234567890"
      Architectures:
        - arm64

  DogWalkingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/build/
      Handler: bootstrap
      Runtime: provided.al2023
      Environment:
        Variables:
          USE_LOCALSTACK: true
          AWS_REGION: eu-west-1
          AWS_ENDPOINT_URL: http://localstack:4566
          AWS_S3_ENDPOINT_URL: http://s3.localhost.localstack.cloud:4566
          DOGS_TABLE_NAME: local-dogs
          DOG_IMAGES_BUCKET: local-dog-images
          CORS_ALLOWED_ORIGIN: http://localhost:3001
          CLOUDFRONT_BASE_URL: http://local-dog-images.s3.localhost.localstack.cloud:4566
      Architectures:
        - arm64
      Timeout: 30
      Events:
        PingAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiNoAuth
            Path: /ping
            Method: GET
        DogsAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /dogs
            Method: POST
        DogsGetAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /dogs/{id}
            Method: GET
        DogsListAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /dogs
            Method: GET
        DogsPutAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /dogs/{id}
            Method: PUT
        DogsDeleteAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /dogs/{id}
            Method: DELETE
        DogsPutPhotoAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /dogs/{id}/photo
            Method: PUT
        DogsDetectBreedAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /dogs/{id}/photo/detect-breed
            Method: POST
        SwaggerUIAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiNoAuth
            Path: /swagger/{proxy+}
            Method: GET