AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      BinaryMediaTypes:
        - image/jpeg
      StageName: dev
      Auth:
        DefaultAuthorizer: LocalAuth
        Authorizers:
          LocalAuth:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt LocalAuthFunction.Arn
            Identity:
              Headers:
                - Authorization


  LocalAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: local-auth/build/
      Handler: bootstrap
      Runtime: provided.al2023
      Environment:
        Variables:
          LOCAL_JWT_SECRET: "1234567890"
      Architectures:
        - arm64

  DogWalkingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/build/
      Handler: bootstrap
      Runtime: provided.al2023
      Environment:
        Variables:
          USE_LOCALSTACK: true
          AWS_REGION: eu-west-1
          AWS_ENDPOINT_URL: http://localstack:4566
          AWS_S3_ENDPOINT_URL: http://s3.localhost.localstack.cloud:4566
          DOGS_TABLE_NAME: local-dogs
          DOG_IMAGES_BUCKET: local-dog-images
      Architectures:
        - arm64
      Timeout: 30
      Events:
        PingAPI:
          Type: HttpApi
          Properties:
            Path: /ping
            Method: GET
        DogsAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /dogs
            Method: POST
        DogsGetAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /dogs/{id}
            Method: GET
        DogsListAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /dogs
            Method: GET
        DogsPutAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /dogs/{id}
            Method: PUT
        DogsDeleteAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /dogs/{id}
            Method: DELETE
        DogsPutPhotoAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /dogs/{id}/photo
            Method: PUT
        DogsDetectBreedAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /dogs/{id}/photo/detect-breed
            Method: POST
