AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DogWalkingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: out/
      Handler: bootstrap
      Runtime: provided.al2023
      Environment:
        Variables:
          USE_LOCALSTACK: true
          AWS_REGION: us-east-1
          AWS_ENDPOINT_URL: http://localstack:4566
          DOGS_TABLE_NAME: local-dogs
      Architectures:
        - arm64
      Timeout: 30
      Events:
        PingAPI:
          Type: HttpApi
          Properties:
            Path: /ping
            Method: GET
        DogsAPI:
          Type: HttpApi
          Properties:
            Path: /dogs
            Method: POST
        DogsListAPI:
          Type: HttpApi
          Properties:
            Path: /dogs
            Method: GET
