// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BreedDetector is an autogenerated mock type for the BreedDetector type
type BreedDetector struct {
	mock.Mock
}

// DetectBreed provides a mock function with given fields: id
func (_m *BreedDetector) DetectBreed(id string) (string, float64, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DetectBreed")
	}

	var r0 string
	var r1 float64
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, float64, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) float64); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewBreedDetector creates a new instance of BreedDetector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBreedDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *BreedDetector {
	mock := &BreedDetector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
