AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the role for GitHub Actions to deploy the Dog Walking service.

Parameters:
  TerraformStateBucket:
    Type: String
    Default: rh-dog-walking-terraform-state
    Description: Name of the S3 bucket used for Terraform state

  GitHubRepository:
    Type: String
    Default: rhargreaves/dog-walking
    Description: GitHub repository in the format owner/repo

  RoleName:
    Type: String
    Description: Name of the IAM role

Resources:
  DeploymentPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DogWalkingDeploymentPolicy
      Description: Policy for deploying the Dog Walking application
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:CreateTable
              - dynamodb:DeleteTable
              - dynamodb:DescribeTable
              - dynamodb:UpdateTable
              - dynamodb:TagResource
              - dynamodb:UpdateContinuousBackups
            Resource: !Sub arn:aws:dynamodb:*:${AWS::AccountId}:table/*-dogs

          - Effect: Allow
            Action:
              - lambda:CreateFunction
              - lambda:DeleteFunction
              - lambda:GetFunction
              - lambda:UpdateFunctionCode
              - lambda:UpdateFunctionConfiguration
              - lambda:AddPermission
              - lambda:RemovePermission
            Resource: !Sub arn:aws:lambda:*:${AWS::AccountId}:function:*-dog-walking-api

          - Effect: Allow
            Action:
              - apigateway:*
            Resource: arn:aws:apigateway:*::/*

          - Effect: Allow
            Action:
              - iam:CreateRole
              - iam:DeleteRole
              - iam:GetRole
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:CreatePolicy
              - iam:DeletePolicy
              - iam:TagRole
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:role/${RoleName}
              - !Sub arn:aws:iam::${AWS::AccountId}:policy/DogWalkingDeploymentPolicy

          - Effect: Allow
            Action:
              - ec2:ModifyVpcAttribute
              - ec2:DescribeAddressesAttribute
              - ec2:CreateVpc
              - ec2:DeleteVpc
              - ec2:CreateSubnet
              - ec2:DeleteSubnet
              - ec2:CreateRouteTable
              - ec2:DeleteRouteTable
              - ec2:CreateRoute
              - ec2:DeleteRoute
              - ec2:CreateInternetGateway
              - ec2:DeleteInternetGateway
              - ec2:CreateNatGateway
              - ec2:DeleteNatGateway
              - ec2:CreateSecurityGroup
              - ec2:DeleteSecurityGroup
              - ec2:AllocateAddress
              - ec2:ReleaseAddress
              - ec2:AssociateRouteTable
              - ec2:DisassociateRouteTable
              - ec2:AttachInternetGateway
              - ec2:DetachInternetGateway
              - ec2:CreateTags
              - ec2:DeleteTags
              - ec2:DescribeVpcs
              - ec2:DescribeSubnets
              - ec2:DescribeRouteTables
              - ec2:DescribeInternetGateways
              - ec2:DescribeNatGateways
              - ec2:DescribeSecurityGroups
              - ec2:DescribeAddresses
            Resource: "*"

          - Effect: Allow
            Action:
              - route53:ChangeResourceRecordSets
              - route53:GetChange
              - route53:ListResourceRecordSets
              - route53:GetHostedZone
            Resource: arn:aws:route53:::hostedzone/*

          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:DeleteLogGroup
              - logs:PutRetentionPolicy
              - logs:DescribeLogGroups
              - logs:TagLogGroup
            Resource: "*"

          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - !Sub arn:aws:s3:::${TerraformStateBucket}
              - !Sub arn:aws:s3:::${TerraformStateBucket}/*

          - Effect: Allow
            Action:
              - acm:RequestCertificate
              - acm:DeleteCertificate
              - acm:DescribeCertificate
              - acm:ListTagsForCertificate
              - acm:AddTagsToCertificate
            Resource: !Sub arn:aws:acm:*:${AWS::AccountId}:certificate/*

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Description: Role for GitHub Actions to deploy the Dog Walking service
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubRepository}:ref:refs/heads/main
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
      ManagedPolicyArns:
        - !Ref DeploymentPolicy

Outputs:
  GitHubActionsRoleArn:
    Description: ARN of the role for GitHub Actions
    Value: !GetAtt GitHubActionsRole.Arn