aws_region         = "eu-west-1"
environment        = "prod"
application_name   = "dog-walking"
api_base_host      = "api.dog-walking.roberthargreaves.com"
images_cdn_host    = "images.dog-walking.roberthargreaves.com"