aws_region       = "eu-west-1"
environment      = "uat"
application_name = "dog-walking"
api_base_host    = "api.uat.dog-walking.roberthargreaves.com"
images_cdn_host  = "images.uat.dog-walking.roberthargreaves.com"