AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DummyApi:   # Here to fix the issue with binary media types
    Type: AWS::Serverless::Api
    Properties:
      BinaryMediaTypes:
        - image/jpeg
      StageName: dev
  DogWalkingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: bootstrap
      Runtime: provided.al2023
      Environment:
        Variables:
          USE_LOCALSTACK: true
          AWS_REGION: eu-west-1
          AWS_ENDPOINT_URL: http://localstack:4566
          AWS_S3_ENDPOINT_URL: http://s3.localhost.localstack.cloud:4566
          DOGS_TABLE_NAME: local-dogs
          DOG_IMAGES_BUCKET: local-dog-images
      Architectures:
        - arm64
      Timeout: 30
      Events:
        PingAPI:
          Type: HttpApi
          Properties:
            Path: /ping
            Method: GET
        DogsAPI:
          Type: HttpApi
          Properties:
            Path: /dogs
            Method: POST
        DogsGetAPI:
          Type: HttpApi
          Properties:
            Path: /dogs/{id}
            Method: GET
        DogsListAPI:
          Type: HttpApi
          Properties:
            Path: /dogs
            Method: GET
        DogsPutAPI:
          Type: HttpApi
          Properties:
            Path: /dogs/{id}
            Method: PUT
        DogsDeleteAPI:
          Type: HttpApi
          Properties:
            Path: /dogs/{id}
            Method: DELETE
        DogsPutPhotoAPI:
          Type: HttpApi
          Properties:
            Path: /dogs/{id}/photo
            Method: PUT
        DogsDetectBreedAPI:
          Type: HttpApi
          Properties:
            Path: /dogs/{id}/photo/detect-breed
            Method: POST
