name: Deploy UAT & Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - '.github/workflows/destroy-uat.yaml'
  workflow_dispatch:

concurrency:
  group: deploy-uat
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  build-api:
    name: Build & Test API
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build API
        run: make build

      - name: Test API
        run: make test-local

      - name: Upload compiled API
        uses: actions/upload-artifact@v4
        with:
          name: bootstrap
          path: api/build/bootstrap

  deploy-uat:
    name: Deploy UAT
    runs-on: ubuntu-latest
    needs: build-api
    environment: uat
    defaults:
      run:
        working-directory: ./infra
    env:
      ENV: uat
      TF_VAR_hosted_zone_id: ${{ secrets.TF_VAR_hosted_zone_id }}
      TF_VAR_sysadmin_password: ${{ secrets.SYSADMIN_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create directory for compiled API
        run: mkdir -p ../api/build

      - name: Download compiled API
        uses: actions/download-artifact@v4
        with:
          name: bootstrap
          path: api/build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Terraform Init
        run: make init

      - name: Terraform Plan
        run: make plan

      - name: Terraform Apply
        run: make apply

  e2e-test-uat:
    name: E2E Test UAT
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: uat
    env:
      ENV: uat

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Run e2e tests
        run: make test
        env:
          COGNITO_USERNAME: ${{ secrets.SYSADMIN_USERNAME }}
          COGNITO_PASSWORD: ${{ secrets.SYSADMIN_PASSWORD }}
