name: Deploy UAT and Run Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-uat:
    name: Deploy UAT
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    env:
      ENV: uat

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Terraform Init
        run: make init

      - name: Terraform Format
        run: make fmt

      - name: Terraform Plan
        run: make plan

      - name: Terraform Apply
        run: make apply

  acceptance-test-uat:
    name: Acceptance Test UAT
    needs: deploy-uat
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run acceptance tests
        run: make test
        env:
          API_HOST: api.uat.dog-walking.roberthargreaves.com