name: Deploy PROD & Test

on:
  workflow_dispatch:

concurrency:
  group: deploy-prod
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    name: Deploy PROD
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: ./infra
    env:
      ENV: prod
      TF_VAR_hosted_zone_id: ${{ secrets.TF_VAR_hosted_zone_id }}
      TF_VAR_sysadmin_password: ${{ secrets.SYSADMIN_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create directory for compiled API
        run: mkdir -p ../api/build

      - name: Download compiled API
        uses: dawidd6/action-download-artifact@v3
        with:
          name: bootstrap
          path: api/build
          workflow: deploy-uat.yaml
          workflow_conclusion: success

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Terraform Init
        run: make init

      - name: Terraform Plan
        run: make plan

      - name: Terraform Apply
        run: make apply

  e2e-test-prod:
    name: E2E Test PROD
    needs: deploy-prod
    runs-on: ubuntu-latest
    environment: prod
    env:
      ENV: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Run e2e tests
        run: make test
        env:
          COGNITO_USERNAME: ${{ secrets.SYSADMIN_USERNAME }}
          COGNITO_PASSWORD: ${{ secrets.SYSADMIN_PASSWORD }}
