name: Destroy UAT

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  id-token: write
  contents: read

jobs:
  destroy-uat:
    name: Destroy UAT
    runs-on: ubuntu-24.04-arm
    environment: uat
    defaults:
      run:
        working-directory: ./infra
    env:
      ENV: uat
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
      SYSADMIN_USERNAME: ${{ secrets.SYSADMIN_USERNAME }}
      SYSADMIN_PASSWORD: ${{ secrets.SYSADMIN_PASSWORD }}
      API_BASE_URL: https://api.uat.dog-walking.roberthargreaves.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Terraform Init
        run: make init

      - name: Terraform Destroy
        run: make destroy
